Bug/crash when reading dont exist
manasv/Evangelium pull request #11
Opened 2020-02-05 06:22 UTC by manasv

**To give context of the problem:**

There's a case when in a date and language, the origin API will provide less readings than expected, and the past solution was tied to specific number of readings so crashed when less where provided.

**The solution:**

Create a factory that delivers objects ready to be procesed by the file manager, based on the number and type of readings passed.

**Important to know:**

As of now the API endpoint is being injected by the CI, for further testing can provide it in private, or in case advice is code quality wise, it can be threaded in here in the review comments.

2020-02-05 14:19 UTC, guseducampos commented on Sources/Evangelium/Helpers/DateManager.swift
> +        dateStringFormatter.locale = NSLocale(localeIdentifier: "en_US_POSIX") as Locale
I think you could `Locale` instead of the NS prefixed

2020-02-05 14:19 UTC, guseducampos commented on Sources/Evangelium/Helpers/ReadingFactory.swift
> +struct ReadingFactory {
since you just have an static function, change this to a enum

2020-02-05 14:19 UTC, guseducampos commented on Sources/Evangelium/Helpers/ReadingFactory.swift
> +        let readings = todayReadings.filter { reading in reading.type == "reading" }
for the `type` it would be better if you use enum for represent the different types you could have

2020-02-05 14:19 UTC, guseducampos commented on Sources/Evangelium/Helpers/ReadingFactory.swift
> +        return SwiftyReading(date: "Invalid")
it would be better if you throw an error here.

2020-02-05 14:19 UTC, guseducampos commented on Sources/Evangelium/Helpers/ReadingFactory.swift
> +        if readings.count == 2 {
you could try using pattern matching here, it could make this a little bit more readable.

2020-02-05 14:19 UTC, guseducampos commented on Sources/Evangelium/Helpers/ReadingFactory.swift
> +        if readings.count == 2 {
You could store the count of the array in a constant in order to avoid call `count` property of the array on each if statement.

2020-02-05 14:19 UTC, guseducampos commented on Sources/Evangelium/Helpers/ReadingFactory.swift
> +    static func create(from todayReadings: [Reading], with date: String) -> SwiftyReading{
add space between `{` and return type

2020-02-06 02:30 UTC, genaro09 commented on Sources/Evangelium/Helpers/ReadingFactory.swift
> +                psalm: !psalm.isEmpty ? psalm.first : nil,
If you are using "filter" to have an array of (psalms, gospel or readings), when "first" is used if the array is ​​empty, the value of this property is null. It is not necessary to check if it is empty.

2020-02-06 02:30 UTC, genaro09 commented on Sources/Evangelium/Helpers/DateManager.swift
> +    init(_ dateString:String) {
add space after ":"

2020-02-23 18:59 UTC, uguizu requested changes

2020-02-23 18:59 UTC, uguizu commented on Sources/Evangelium/Helpers/ReadingFactory.swift
> +            }
To eliminate that if-else block, you could do something like:
```
return SwiftyReading(
                firstReading: todayReadings.first?.type == .some(.reading) ? readings.first : nil ,
                psalm: psalm,
                secondReading: todayReadings.first?.type != .some(.reading) ? readings.first : nil,
                gospel: gospel,
                date: date
}
```

2020-02-23 20:13 UTC, guseducampos approved these changes

2020-02-23 20:13 UTC, guseducampos commented on Sources/Evangelium/Helpers/ReadingFactory.swift
> +        switch  numberOfReadings {
it will be more readable if you use an enum here instead just plain `Ints`

2020-02-23 20:21 UTC, genaro09 approved these changes

2020-02-23 22:07 UTC, uguizu approved these changes

2020-02-23 22:25 UTC, merged